sudo: required
services:
  - docker

before_install:
  - docker build -t dingyj3178/docker-react -f Dockerfile.dev .

script:
  - docker run dingyj3178/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-515576782386'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
